import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import themeConfig from "./themeConfig";

import { open_sans } from "@/fe-global/assets/fonts";
import { ProviderRedux } from "@/app/stores/providers";
import { ThemeProvider } from "@/fe-global/themes/ThemeProvider";

export const metadata: Metadata = {
  title: "Airagent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        <AntdRegistry>
          <ThemeProvider theme={themeConfig}>
            <ProviderRedux>{children}</ProviderRedux>
          </ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
